### ISSUE TITLE
Leave typenames the way they are defined in queries for Flow/Typescript targets

### ISSUE THREAD

**Issue by chrishandorf** [apollographql/apollo-codegen#92] opened 2017-04-21 13:20 UTC
I'm on the latest release as of this writing:  apollo-codegen@0.10.11

I have a Product Bill Of Materials (BOM) structure named as follows:

GraphQL input
==============
input InputProductBOMItem {
  ...
}

Generated interface
==================
export interface InputProductBomItem {    // The "om" should NOT be lower case
  ...
}

This causes errors everywhere InputProductBOMItem is referenced.

**Comment by lewisf** [comment] 2017-04-23 03:34
Thanks for reporting! This is a duplicate of #72.

**Comment by chrishandorf** [comment] 2017-04-24 12:08
@lewisf I thought it was a duplicate too, but #72 was fixed and released with #79 wasn't it?  I'm running the latest release 0.10.11 and its still happening.

**Comment by chrishandorf** [comment] 2017-04-24 12:10
@lewisf I think the difference here is that this string is neither camelCase nor PascalCase.  Why doesn't the apollo-codegen just leave all type names as-is rather than trying to modify them?

**Comment by lewisf** [comment] 2017-04-24 17:15
@chrishandorf I think it's because popular style guides have recommended a style for both flow/typescript which is why this was added, but I agree that it leads to a lot of unpredictability with the type names.

I'd like to personally move it to just use names as is. Maybe we should discuss rather or not that is better behavior in general for developer experience?

**Comment by lewisf** [comment] 2017-05-09 18:33
I just changed this to an issue and we're going to consolidate all discussion around casing here, which includes: #72, #63

**Comment by blargity** [comment] 2017-07-04 13:08
We also have a case where we'd like to namespace with underscores since everything ends up in one file:

If I name the query `SomeComponent_GetThing` it gets generated as `SomeComponentGetThingQuery` which is harder to read, and I'd like it to leave the names I give alone if possible.

Of course even more amazing would be if it could generate the types alongside the query file rather than jamming them all into a single file so we don't have to namespace them in the first place and can just import the correct ones where they're needed. 👍

**Comment by rricard** [comment] 2017-07-18 18:47
@lewisf just added it the 1.0 milestone, this is indeed a bug, we should not enforce conventions since it breaks the query naming.

@martijnwalraven do you see any issues with the swift target if we stop enforcing this? We can eventually keep it only for swift...

**Comment by martijnwalraven** [comment] 2017-07-18 21:20
@rricard: As far as I know, the case conversions are part of the individual targets and not the compiler, so there shouldn't be any issue removing them from TypeScript/Flow.

**Comment by rricard** [comment] 2017-07-18 21:45
Okay, so let's only target flow and TS on this issue

**Comment by rricard** [comment] 2017-07-25 18:51
I'm going to do it since it has been one week without anyone claiming the issue and this needs to be fixed.

**Closed** 2017-07-25 20:18 UTC
Labels: bug, easy, flow, help wanted, typescript

**Comment by leethree** [comment] 2017-07-31 07:40
This change broke our current workflow because we use camelCase for fragment/query names but PascalCase for Flow type names. Forced-pascal-casing worked great for us. Is there any chance that you could make it into an option?

**Comment by rricard** [comment] 2017-08-01 18:40
@leethree adding options is a good escape hatch to make everyone happy and makes sense when we're approaching a transform that considerably changes the output... However, since we're trying to stabilize this project, adding too much options keeps a great level of branching throughout the project. I would advise you to stay on the version before this one, migrate all non-enforced pascal case names or, use types in camelCase, and migrate back to this version.

**Comment by leethree** [comment] 2017-08-02 03:14
@rricard OK. thanks for the advice!

**Comment by rricard** [comment] 2017-08-02 08:27
@leethree I'm still trying to figure out how we could handle options more easily and gracefully so someone can do a PR to adress the problem you have if needed. All I want is have everything properly structured and documented.
