### ISSUE TITLE
Making array object types optional may have been a mistake in flow types generation.

### ISSUE THREAD

**Issue by epicallan** [apollographql/apollo-codegen#225] opened 2017-08-09 15:56 UTC
In version [0.15 we had this in the test snapshots](https://github.com/apollographql/apollo-codegen/blob/c866a123f1da367994dcd00219fae970e4113328/test/flow/__snapshots__/codeGeneration.js.snap#L51)
```
{
      friends: ?Array< ( {
          __typename: \\"Human\\",
          // The name of the character
          name: string,
        }
```
In the most recent version of the lib you have flow types as such

````
 friends: ?Array< ?( {
          __typename: \\"Human\\",
          // The name of the character
          name: string,
        } >,
````

the new change that makes the array object optional just introduces a lot of type / value checking complications.

When I cross check in the typescript generated types, the array object is not optional. The type is similar to what we had in v0.15 in flow types.

This makes me wonder whether this new change in v0.16 was intentional ? If it wasn't could we revert to the earlier version for this. I can put together a PR

**Comment by dperetti** [comment] 2017-09-25 12:45
100% agree ! It's even worse when you have a Relay interface and you need to traverse edges and nodes, all optional (for no obvious reason)... and Flow gets lost even if you unwrap the values properly.

**Comment by dperetti** [comment] 2017-10-03 19:12
This is crazy, it makes the whole thing barely usable !

**Comment by epicallan** [comment] 2017-10-03 19:16
Its strange it hasn't got any attention from the library authors, maybe submitting a PR would do. Personally i just rolled back at 0.15 and I have not attempted to update since then.

**Comment by dperetti** [comment] 2017-10-03 19:19
Now we know who the two users of apollo-codegen are ! 😅

**Comment by martijnwalraven** [comment] 2017-10-03 19:21
@dperetti @epicallan: Yeah, a PR would be great!

**Comment by epicallan** [comment] 2017-10-03 20:47
@martijnwalraven I have submitted PR #263

**Comment by martijnwalraven** [comment] 2017-10-04 02:33
@epicallan: Looking at your PR, I realized this is actually expected behavior. Whether array elements are non-nullable is part of the schema, and in this case [`friends` is defined as `[Character]`](https://github.com/apollographql/apollo-codegen/blob/337b6b76d313d1fbf5515958552d5cb0585ca8de/test/fixtures/starwars/schema.graphql#L35), meaning an optional array of optional elements.

Since the server is allowed to send you `null` for any of the elements, that is something you want to make explicit in the generated types so you can deal with it appropriately. In many cases of course, an array element being `null` doesn't make sense. But that means the type should be fixed in the schema, changing `friends` to `[Character!]` here for example.

**Comment by epicallan** [comment] 2017-10-04 03:57
Thanks @martijnwalraven that makes sense.

**Comment by lydell** [comment] 2017-10-21 12:21
I consider it a feature that apollo-codegen follows the schema definition and adds `?` to everything that can be nullable (so IMO this issue can be closed). I'm fine with the extra null-checking in the code I've written so far.

**Comment by martijnwalraven** [comment] 2017-10-21 15:43
@lydell: Good to hear, closing this issue!

**Closed by martijnwalraven** 2017-10-21 15:43 UTC
